trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      #!/bin/bash

      # Set the Xcode project and workspace paths
      XCODE_PROJECT_PATH="**/*.xcodeproj"
      XCODE_WORKSPACE_PATH="**/*.xcodeproj/project.xcworkspace"

      # Set the scheme and configuration
      SCHEME="Runner"
      CONFIGURATION="Release"

      # Set the archive path
      ARCHIVE_PATH="./Runner.xcarchive"

      # Set the signing options
      CODE_SIGN_STYLE="Manual"
      CODE_SIGN_IDENTITY="iPhone Distribution"
      PROVISIONING_PROFILE="H93F57BRA4"

      # Archive the Xcode project
      xcodebuild \
        -workspace "$XCODE_WORKSPACE_PATH" \
        -scheme "$SCHEME" \
        -sdk iphoneos \
        -configuration "$CONFIGURATION" \
        archive \
        -archivePath "$ARCHIVE_PATH" \
        CODE_SIGN_STYLE="$CODE_SIGN_STYLE" \
        CODE_SIGN_IDENTITY="$CODE_SIGN_IDENTITY" \
        PROVISIONING_PROFILE="$PROVISIONING_PROFILE"
