trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- script: |
    flutter build ios
    xcodebuild archive -workspace '**/ios/Runner.xcworkspace' -scheme 'Runner' -configuration 'Release' -sdk 'iphoneos' -archivePath './Runner.xcarchive' CODE_SIGN_STYLE='Manual' DEVELOPMENT_TEAM='YOUR_TEAM_ID' CODE_SIGN_IDENTITY='iPhone Distribution' PROVISIONING_PROFILE_SPECIFIER='H93F57BRA4'
  displayName: 'Archive'
